# Generated by Django 3.0 on 2019-12-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotrip_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=80),
        ),
    ]
